version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - localoceandb1:/docker-entrypoint-initdb.d # This will import DB data from an sql file in your /data folder
            - localoceandbmigratesql1:/docker-entrypoint-initdb.d/data/migrate.sql # run sql commands in migrate.sql to update site urls in DB
        restart: always
        ports:
            - "3400:3306" # mapping our ports for networking
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: password
    wordpress:
        build:
          context: .
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "3500:80" # mapping our ports for networking
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306 # Docker will automatically update the wp-config file with these details when using a WordPress image
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        volumes: # this is where we tell Docker what to pay attention to
            - localoceanwptheme1:/var/www/html/wp-content/themes/my-theme-name # map theme to container
            - localoceanwpplugins1:/var/www/html/wp-content/plugins # map plugins to container
            - localoceanwpuploads1:/var/www/html/wp-content/uploads # map uploads to container
volumes:
    localoceandb1:
    localoceandbmigratesql1:
    localoceanwptheme1:
    localoceanwpplugins1:
    localoceanwpuploads1: